name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main   # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Clone HF Space repo
        run: |
          git clone https://huggingface.co/spaces/darsh-reddy-v/talentscout-ai hf-space
        env:
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}

      - name: Copy files to HF Space repo
        run: |
          rsync -av --delete --exclude '.git' ./ hf-space/

      - name: Commit & push changes to HF Space
        run: |
          cd hf-space
          git add .
          git commit -m "Deploy from GitHub Actions" || echo "No changes to commit"
          git push origin main
        env:
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
